[tool.poetry]
name = "AI-POC"
version = "0.1.0"
description = ""
authors = ["https://github.com/AleksNeStu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"
requests = "^2.32.3"
opencv-python = "^4.10.0.84"
tenacity = "^8.4.2"
matplotlib = "^3.9.0"
langchain = "^0.2.6"
diffusers = "^0.29.2"
transformers = "^4.42.3"
scipy = "^1.14.0"
ftfy = "^6.2.0"
mypy = "^1.10.1"
ruff = "^0.5.0"
black = "^24.4.2"
ipykernel = "^6.29.5"
torch = "^2.3.1"
jupyter = "^1.0.0"
fastapi = "^0.111.0"
accelerate = "^0.32.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
